language: node_js
node_js:
- 10.15.0
cache:
  directories:
    - node_modules
dist: trusty
before_install:
  - npm install -g yarn
install:
  - yarn install
script:
  - yarn test
  - yarn build
notifications:
  email:
  - ebrehault@gmail.com
